openapi: 3.0.0
info:
  description: API for retrieving Marvel characters.
  version: 1.0.0
  title: Character API
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /
tags:
  - name: Character
    description: Retrieval API for a list of characters by Marvel.
paths:
  '/character':
    get:
      tags:
        - Character
      summary: Returns all characters as a list of their identifiers.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/characters'
        '404':
          description: Failed. Characters not ready to serve yet.
        '500':
          description: Failed. Internal server error.
    
  '/character/{character_id}':
    get:
      tags:
        - Character
      summary: Retuns details of a specific character by given identifier
      parameters:
        - name: character_id
          in: path
          required: true
          description: ID of the character
          schema:
            type: string
        - name: language
          in: query
          required: false
          description: Target language code (ISO-639-1) to translate descripttion to.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/character'
        '404':
          description: Failed. Character not found.
        '500':
          description: Failed. Internal server error.
    
components:
  schemas:
    character_id:
      properties:
        uuid:
          type: string
    character:
      type: object
      properties:
        id:
          type: string
          format: string
        name:
          type: string
          format: string
        description:
          type: string
          format: string
        thumbnail:
          type: object
          properties:
            path:
              type: string
              format: string
            extension:
              type: string
              format: string
    characters:
      type: object
      properties:
        character:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/character_id'
   

